#-------------------------------
# General Site Settings
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Gerous"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 6


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Resources"
    weight = 4
    hasChildren = true

  [[menu.main]]
    parent = "Resources"
    name = "News"
    url = "/tags/news/"
    weight = 1

  [[menu.main]]
    parent = "Resources"
    name = "Games"
    url = "/tags/games/"
    weight = 2

  [[menu.main]]
    parent = "Resources"
    name = "Mobile"
    url = "/tags/mobile/"
    weight = 3

  [[menu.main]]
    parent = "Resources"
    name = "Elements"
    url = "/elements/"
    weight = 4

  [[menu.main]]
  name = "About Me"
  url = "/about/"
  weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.footer]]
    name = "Posts"
    url = "/posts/"
    weight = 3

  [[menu.footer]]
    name = "About Me"
    url = "/about/"
    weight = 4


  # Call to action button
  [params.cta_button]
    enable = true
    cta_button_link = "/contact/"
    cta_button_text = "Get in touch"


[params]
  logo = "/images/logo.png" # You can add own logo. For example "/images/logo.png".
  logo_dark = "/images/logo.png"
  description = "Gerous is a modern portfolio Hugo theme"
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


  #-------------------------------
  # Author Settings
  [params.author]
    author_name = "Daryl Mercer"
    author_avatar = "https://via.placeholder.com/100x100"


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero_title = "I'm an expert user experience strategist and mobile developer."
    hero_description = "Leveraging my expertise, I'm here to collaborate with you on crafting design solutions that transcend expectations. Let's embark on a journey of innovation together!"

  [params.hero_logos]
    enable = true

  [[params.hero_logo_image]]
    image_alt = "Apple Logo"
    image_url = "https://via.placeholder.com/80x80"

  [[params.hero_logo_image]]
    image_alt = "Adobe Logo"
    image_url = "https://via.placeholder.com/80x80"

  [[params.hero_logo_image]]
    image_alt = "HP Logo"
    image_url = "https://via.placeholder.com/80x80"

  [[params.hero_logo_image]]
    image_alt = "Netlify Logo"
    image_url = "https://via.placeholder.com/80x80"

  [[params.hero_logo_image]]
    image_alt = "Dropbox Logo"
    image_url = "https://via.placeholder.com/80x80"

  [[params.hero_logo_image]]
    image_alt = "EA Logo"
    image_url = "https://via.placeholder.com/80x80"

  [[params.hero_logo_image]]
    image_alt = "Chrome Logo"
    image_url = "https://via.placeholder.com/80x80"


  #-------------------------------
  # Slider Featured Settings
  [params.featured]
    enable = true
    featured_title = "Selected Work"


  #-------------------------------
  # Projects Settings
  [params.projects]
    enable = true
    projects_title= "Recent Work"
    projects_description= ""


  #-------------------------------
  # Testimonials Section
  [params.testimonials]
    enable = true
    testimonials_intro = "Don't take my word for it"
    testimonials_title = "See what our happy clients say..."
    testimonials_info = "Join over <b>10K+</b> Prefessionals"

  [[params.testimonial_item]]
    name = "Martin Vetrovs"
    image = "https://via.placeholder.com/120x120"
    designation = "Data Scientist"
    title = "Incredible attention to detail"
    content = "The incredible attention to detail displayed by this team is commendable. Every aspect of our project, no matter how small, was handled with precision and care. The result is a product that reflects their commitment to excellence."

  [[params.testimonial_item]]
    name = "Hanna Herwitz"
    image = "https://via.placeholder.com/120x120"
    designation = "UI/UX Designer"
    title = "Collaborative partnership"
    content = "Our partnership with this team was characterized by open communication and collaborative efforts. They took the time to understand our goals and delivered a solution that perfectly aligns with our business objectives. Looking forward to future collaborations."

  [[params.testimonial_item]]
    name = "Carter Curtis"
    image = "https://via.placeholder.com/120x120"
    designation = "DevOps Engineer"
    title = "Creative brilliance unleashed"
    content = "Working with this creative powerhouse was an enlightening experience. Their brilliance in design thinking and creative solutions brought our project to life in ways we hadn't imagined. The team's passion for innovation is truly infectious."

  [[params.testimonial_item]]
    name = "Marcus Vaccaro"
    image = "https://via.placeholder.com/120x120"
    designation = "Systems Analyst"
    title = "Efficient problem solvers"
    content = "This team proved to be efficient problem solvers throughout our project. When faced with challenges, they tackled them with creativity and resourcefulness. Their ability to overcome obstacles ensured a smooth and successful project delivery."


  #-------------------------------
  # Faq (Frequently asked questions) Settings
  [params.faq]
    enable = true
    faq_intro = "Need some answers?"
    faq_title = "Frequently asked questions"

  [[params.faq_item]]
    title = "What distinguishes you as a mobile developer?"
    description = "I bring a wealth of experience in crafting seamless user experiences and developing mobile solutions that prioritize functionality and innovation."

  [[params.faq_item]]
    title = "How do you approach designing user-friendly mobile applications?"
    description = "My approach involves a user-centric design philosophy, focusing on intuitive interfaces and fluid interactions to enhance the overall mobile experience."

  [[params.faq_item]]
    title = "Can you walk us through your mobile app development process?"
    description = "Certainly! From concept to deployment, I follow a structured development process, incorporating user feedback and iterative testing to ensure a polished and functional mobile application."

  [[params.faq_item]]
    title = "How do you stay updated on the latest trends mobile development?"
    description = "Continuous learning is key. I stay updated through industry publications, attending conferences, and actively participating in professional communities to stay at the forefront of industry trends."

  [[params.faq_item]]
    title = "How do you ensure the security of mobile applications you develop?"
    description = "Security is a top priority. I follow industry best practices, conduct thorough testing, and implement robust security measures to safeguard mobile applications and user data."

  [[params.faq_item]]
    title = "What role does user feedback play in your development process?"
    description = "User feedback is integral. I actively seek and incorporate user insights to refine designs and optimize mobile applications, ensuring they align with user expectations and preferences."


  #-------------------------------
  # Blog Section
  [params.blog]
    enable = true
    blog_intro = "What‚Äôs new?"
    blog_title = "Latest from blog"


  #-------------------------------
  # Author Section Settings
  [params.author_section]
    enable = true
    author_section_title = "Hi there üëã ! Welcome to my fun zone. I'm Daryl, the playmaker of ideas."
    author_section_description = "When I'm not crafting digital wonders, you can catch me sipping on coffee, cruising around on my bike, diving into games, and grooving to some tunes. Let's connect, share stories, and make this digital space our cozy corner. Cheers to good vibes and creative adventures!"
    author_section_image = "https://via.placeholder.com/1600x1600"
    author_section_image_alt = "Daryl Mercer"
    author_section_button_text = "Let's —Åonnect!"
    author_section_button_link = "/contact"


  #-------------------------------
  # Footer Settings

  # Social Links
  [[params.social]]
    icon = "fa-brands fa-facebook-f"
    name = "Facebook"
    link = "https://facebook.com"

  [[params.social]]
    icon = "fa-brands fa-x-twitter"
    name = "Twitter"
    link = "https://twitter.com"

  [[params.social]]
    icon = "fa-brands fa-tiktok"
    name = "Tiktok"
    link = "https://www.tiktok.com/"

  [[params.social]]
    icon = "fa-brands fa-instagram"
    name = "Instagram"
    link = "https://instagram.com"



  # Example of adding a new link to the footer section:
  # [[params.social]]
  #   icon = "fa-brands fa-vimeo"
  #   name = "Vimeo"
  #   link = "https://vimeo.com"

  # Other icons can be found at https://fontawesome.com/icons


  # Newsletter
  [params.mailchimp]
    enable = true
    mailchimp_title = "Stay inspired weekly üì¨ Your friendly dose of tips & insights!"
    mailchimp_description = "Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox."
    mailchimp_identifier = "gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp" # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
    mailchimp_input_text = "Your email address"


  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "your@email.com" # Add your form_id

    # NOTE
    # Gerous comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = true
    disqusShortname = "anvod-studio-test" # Add your shortname for Disqus Comment. For example anvod-studio-test


[taxonomies]
  tag = "tags"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false